export const dynamic = "force-dynamic"

interface SearchResult {
  id: string
  title?: string
  description?: string
  category?: string
  relevance?: number
  content?: string
  tags?: string[]
  metadata?: Record<string, unknown>
  source?: string
  createdAt?: string
}

interface SearchApiResponse {
  results: SearchResult[]
  query: string
  count: number
}

interface ChatRequestBody {
  query?: string
  topK?: number
}

interface ChatResponseBody {
  query: string
  answer: string
  results: SearchResult[]
}

export async function POST(req: Request) {
  let body: ChatRequestBody
  try {
    body = await req.json()
  } catch {
    return Response.json({ error: "Invalid JSON body" }, { status: 400 })
  }

  const query = body.query?.trim()
  if (!query) {
    return Response.json({ error: "Query is required" }, { status: 400 })
  }

  const topK = body.topK && body.topK > 0 ? Math.min(body.topK, 20) : 5

  try {
    const url = new URL(req.url)
    const searchResponse = await fetch(`${url.origin}/api/search?q=${encodeURIComponent(query)}`)

    if (!searchResponse.ok) {
      throw new Error(`Search API error: ${searchResponse.status}`)
    }

    const searchData = (await searchResponse.json()) as SearchApiResponse
    const allResults = Array.isArray(searchData.results) ? searchData.results : []
    const selected = allResults.slice(0, topK)

    const relevanceThreshold = 0.2
    const hasUsefulChunks =
      selected.length > 0 &&
      selected.some((r) => typeof r.relevance === "number" && r.relevance >= relevanceThreshold)

    const context = selected
      .map((r, index) => {
        const score = typeof r.relevance === "number" ? Math.round(r.relevance * 100) : null
        const header =
          score !== null
            ? `Chunk ${index + 1} (relevance: ${score}%)`
            : `Chunk ${index + 1}`
        const source = r.source ? `\nSource: ${r.source}` : ""
        return `${header}\n${r.content || r.description || ""}${source}`
      })
      .join("\n\n")

    const ollamaUrl = process.env.OLLAMA_URL || "http://localhost:11434"
    const model = process.env.OLLAMA_MODEL || "gpt-oss:20b"

    const noContextDisclaimer =
      "Note: No relevant reference chunks were found in the database for this query. The following answer is based on general knowledge:"

    let prompt: string

    if (hasUsefulChunks) {
      prompt = `You are a helpful assistant answering questions using the provided reference chunks from a document database.

User question:
${query}

Reference chunks (numbered):
${context}

Instructions for your answer:
- Treat the reference chunks as your primary source of truth.
- Prefer information from the chunks over your general knowledge; do NOT contradict the chunks.
- At the beginning of your answer, explicitly cite which chunks you are using, for example: "Based on chunks 1 and 3".
- When you supplement the chunks with your general knowledge, clearly mark those parts as coming from "general knowledge".
- If the answer is uncertain or not supported by either the chunks or your general knowledge, say so explicitly.`
    } else {
      prompt = `You are a helpful assistant that must answer using your general knowledge because no relevant reference chunks were found in the database.

User question:
${query}

Instructions for your answer:
- You do NOT have any useful database context for this query.
- Answer using your general knowledge instead.
- At the very beginning of your answer, include exactly this line:
"${noContextDisclaimer}"
- After that line, provide your best answer.
- Be explicit if you are uncertain or if information might be incomplete.`
    }

    const llmResponse = await fetch(`${ollamaUrl}/api/generate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model,
        prompt,
        stream: false,
      }),
    })

    if (!llmResponse.ok) {
      throw new Error(`Ollama error: ${llmResponse.status}`)
    }

    const llmData = (await llmResponse.json()) as { response?: string }
    let answer = (llmData.response || "").trim() || "No response was generated by the model."

    if (!hasUsefulChunks && answer) {
      if (!answer.startsWith(noContextDisclaimer)) {
        answer = `${noContextDisclaimer}\n\n${answer}`
      }
    }

    const payload: ChatResponseBody = {
      query,
      answer,
      results: selected,
    }

    return Response.json(payload)
  } catch (error) {
    console.error("Error in /api/chat:", error)
    return Response.json(
      { error: "Failed to process chat request. Please try again later." },
      { status: 500 },
    )
  }
}

